from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from io import BytesIO
from datetime import datetime

class ReportGenerator:
    def generate_student_report(self, student_name: str, reg_no: str, attendance_records: list):
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        elements = []
        
        # Styles
        styles = getSampleStyleSheet()
        title_style = ParagraphStyle(
            'Title',
            parent=styles['Heading1'],
            fontSize=24,
            textColor=colors.HexColor('#06b6d4'), # Cyan
            spaceAfter=20,
            alignment=1 # Center
        )
        
        # Header
        elements.append(Paragraph("Holo Auth Report", title_style))
        elements.append(Paragraph(f"Student Attendance Record", styles['Heading2']))
        elements.append(Spacer(1, 10))
        
        # Student Info
        elements.append(Paragraph(f"<b>Name:</b> {student_name}", styles['Normal']))
        elements.append(Paragraph(f"<b>Reg No:</b> {reg_no}", styles['Normal']))
        elements.append(Paragraph(f"<b>Generated On:</b> {datetime.now().strftime('%Y-%m-%d %H:%M')}", styles['Normal']))
        elements.append(Spacer(1, 20))
        
        # Table Data
        data = [['Date', 'Time', 'Status', 'Method']]
        
        present_count = 0
        for record in attendance_records:
            date_str = record.timestamp.strftime('%Y-%m-%d')
            time_str = record.timestamp.strftime('%H:%M:%S')
            status = record.verification_status
            method = record.verification_method
            
            if status == 'success':
                present_count += 1
                
            data.append([date_str, time_str, status.upper(), method])
            
        # Summary
        total = len(attendance_records)
        percentage = (present_count / total * 100) if total > 0 else 0
        
        elements.append(Paragraph(f"<b>Total Classes:</b> {total} | <b>Present:</b> {present_count} ({percentage:.1f}%)", styles['Heading3']))
        elements.append(Spacer(1, 15))

        # Table Style
        table = Table(data, colWidths=[100, 100, 100, 150])
        table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1f2937')), # Header Grey
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
            ('BACKGROUND', (0, 1), (-1, -1), colors.white),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f3f4f6')])
        ]))
        
        elements.append(table)
        
        # Footer
        elements.append(Spacer(1, 30))
        elements.append(Paragraph("Generated by Holo Biometric System", styles['Italic']))
        
        doc.build(elements)
        buffer.seek(0)
        return buffer
